apiVersion: v1
kind: Pod
metadata:
 name: kafka-app
 namespace: default
spec:
 containers:
 - name: kafka-app
   image: 443602378074.dkr.ecr.eu-central-1.amazonaws.com/myapp:latest
   ports:
     -  containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    name: kafka-app
