---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ekswork-eksctl
  region: eu-central-1
  version: "1.19"

availabilityZones: ["eu-central-1a", "eu-central-1b", "eu-central-1c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 4
  instanceType: t3.medium
  ssh:
    enableSsm: true

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:eu-central-1:443602378074:key/40b56115-9196-40a3-ae43-cf33d710ffd6
